---
- name: uninstalling a httpd
  hosts: all
  become: true
  tasks:
  - name: Stop service httpd
    service:
      name: httpd
      state: stopped

  - name: uninstaling a httpd 
    yum:
      name: httpd
      state: removed

